### ISSUE TITLE
use es-class to enable using a polyfill in ES3 environment

### ISSUE THREAD

**Issue by marcelh-gh** [WebReflection/es-class#4] opened 2017-04-26 11:42 UTC
@WebReflection

Hi Andrea,

I have been trying to get a polyfill for array.find running in an ES3 (Acrobat) environment which does not have Object.defineproperty.

I came across your es-class and it seemed like a great solution to my problem.
Unfortunately, I cant get it to work. Am I mistaken, that I can simply paste your code in front of the polyfill and it should be using your Object.defineproperty method?

Thanks a lot & best regards,
Marcel

**Comment by WebReflection** [comment] 2017-04-26 11:49
> I came across your es-class and it seemed like a great solution to my problem.

not sure I understand how es-class can solve your array.find polyfill issue


> Am I mistaken, that I can simply paste your code in front of the polyfill and it should be using your Object.defineproperty method?

you are, es-class does not pollute the global Object, it creates a fallback for its own scope.

I think you are rather looking for es5-shim and es5-sham ?

https://github.com/es-shims/es5-shim

I'll close this unless there is some code that demonstrate there is a bug.

**Closed as completed by WebReflection** 2017-04-26 11:49 UTC

**Comment by marcelh-gh** [comment] 2017-04-26 12:37
thanks for the quick reply. I had looked into the es5shims & shams before without success. in the meantime I also found your blogpost about the issues with any kind of Object.defineproperty polyfills.
Seems, it's just not worth the effort! ;-)

**Comment by WebReflection** [comment] 2017-04-26 13:16
why do you need an Array.prototype.find method and why don't you just add it ?

Array are never looped through `for/in` ... or better, should never be looped like that.

**Comment by marcelh-gh** [comment] 2017-04-26 13:42
sure, just adding a Array.prototype.find is not the problem. my problem was that i could make sure that the added prototype property is not enumerable in all array instances.

based on your comment i just did some quick checks. it seems that is ONLY a problem if for/in loops are used.
is that what you are saying? if no for/in loop is used on an array in the entire project, the polyfill is ok?

you said, arrays should never looped via for/in. is there another reason than this particular issue?

thanks a lot!

BTW: are you still working on your BENJA project? seems pretty cool!

**Comment by marcelh-gh** [comment] 2017-04-26 13:50
ok, after a quick search I know why for/in might be a bad idea for arrays. ;-)
I am actually coding in TypeScript and only end up with ES3 after several transpiling steps.
I use .foreach with an arrow function for arrays most of the time. I did use for/in loops to replace some "traditional" for loops for convenience when i migrated an older code base.

**Comment by WebReflection** [comment] 2017-04-26 14:27
> if no for/in loop is used on an array in the entire project, the polyfill is ok?

yes, and if you use `for/in` you probably have a `obj.hasOwnProperty(key)` guard too because that's how you usually loop `for/in`

In that case polluting the prototype with an enumerable method is fine.

The problem is that you are behind a transpiler and unless you are sure about its generated code, you're not safe so ... it's your call.

> BTW: are you still working on your BENJA project? seems pretty cool!

BENJA doesn't need much maintenance, it's an ArchLinux bootstrap. In the worst case scenario you rename `/home/benja/app/package.json` to `/home/benja/app/package.jsoff`, do a `sudo pacman -Syu` and an `npm update -g` followed by `npm update` and reboot with a whole freshly new updated system 🎉
